server:
  port: 8081

spring:
  application:
    name: STOCK-PRICE-API
  config:
    import: optional:configserver:http://localhost:9080
    
#  boot:
#    admin:
#      client:
#        url: http://localhost:1111/
##  eureka:
##    client:
##      serviceUrl:
##        defaultZone: http://localhost:8761/
#  
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/company_stock_price_db
#    username: your_db_rootname
#    password: your_db_password
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#  
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
        
       
